"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_moving_target_teleop_command(object):

    __slots__ = ["utime", "timestamp_millis", "throttle", "turn", "stop"]

    __typenames__ = ["int64_t", "int64_t", "double", "double", "boolean"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.timestamp_millis = 0
        """ LCM Type: int64_t """
        self.throttle = 0.0
        """ LCM Type: double """
        self.turn = 0.0
        """ LCM Type: double """
        self.stop = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_moving_target_teleop_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqddb", self.utime, self.timestamp_millis, self.throttle, self.turn, self.stop))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_moving_target_teleop_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_moving_target_teleop_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_moving_target_teleop_command()
        self.utime, self.timestamp_millis, self.throttle, self.turn = struct.unpack(">qqdd", buf.read(32))
        self.stop = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_moving_target_teleop_command in parents: return 0
        tmphash = (0x54d51f9b38d28863) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_moving_target_teleop_command._packed_fingerprint is None:
            lcmt_moving_target_teleop_command._packed_fingerprint = struct.pack(">Q", lcmt_moving_target_teleop_command._get_hash_recursive([]))
        return lcmt_moving_target_teleop_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_moving_target_teleop_command._get_packed_fingerprint())[0]

