"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_moving_target_actuation_command(object):

    __slots__ = ["utime", "timestamp_millis", "left_drive_torque", "right_drive_torque"]

    __typenames__ = ["int64_t", "int64_t", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.timestamp_millis = 0
        """ LCM Type: int64_t """
        self.left_drive_torque = 0.0
        """ LCM Type: double """
        self.right_drive_torque = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_moving_target_actuation_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqdd", self.utime, self.timestamp_millis, self.left_drive_torque, self.right_drive_torque))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_moving_target_actuation_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_moving_target_actuation_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_moving_target_actuation_command()
        self.utime, self.timestamp_millis, self.left_drive_torque, self.right_drive_torque = struct.unpack(">qqdd", buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_moving_target_actuation_command in parents: return 0
        tmphash = (0x90556b0f28e798b8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_moving_target_actuation_command._packed_fingerprint is None:
            lcmt_moving_target_actuation_command._packed_fingerprint = struct.pack(">Q", lcmt_moving_target_actuation_command._get_hash_recursive([]))
        return lcmt_moving_target_actuation_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_moving_target_actuation_command._get_packed_fingerprint())[0]

