"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_wind_parameters(object):

    __slots__ = ["nominal_wind", "gust_sigma", "altitude", "drag_coeff"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [[3], [3], None, None]

    def __init__(self):
        self.nominal_wind = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.gust_sigma = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.altitude = 0.0
        """ LCM Type: double """
        self.drag_coeff = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_wind_parameters._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.nominal_wind[:3]))
        buf.write(struct.pack('>3d', *self.gust_sigma[:3]))
        buf.write(struct.pack(">dd", self.altitude, self.drag_coeff))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_wind_parameters._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_wind_parameters._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_wind_parameters()
        self.nominal_wind = struct.unpack('>3d', buf.read(24))
        self.gust_sigma = struct.unpack('>3d', buf.read(24))
        self.altitude, self.drag_coeff = struct.unpack(">dd", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_wind_parameters in parents: return 0
        tmphash = (0x1428042345d945c4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_wind_parameters._packed_fingerprint is None:
            lcmt_wind_parameters._packed_fingerprint = struct.pack(">Q", lcmt_wind_parameters._get_hash_recursive([]))
        return lcmt_wind_parameters._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_wind_parameters._get_packed_fingerprint())[0]

