"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_quadrotor_command(object):

    __slots__ = ["utime", "rotor_input"]

    __typenames__ = ["int64_t", "double"]

    __dimensions__ = [None, [4]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.rotor_input = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_quadrotor_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>4d', *self.rotor_input[:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_quadrotor_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_quadrotor_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_quadrotor_command()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.rotor_input = struct.unpack('>4d', buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_quadrotor_command in parents: return 0
        tmphash = (0xa4e0fab2147b9e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_quadrotor_command._packed_fingerprint is None:
            lcmt_quadrotor_command._packed_fingerprint = struct.pack(">Q", lcmt_quadrotor_command._get_hash_recursive([]))
        return lcmt_quadrotor_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_quadrotor_command._get_packed_fingerprint())[0]

