"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_camera_command(object):

    __slots__ = ["pitch_rad"]

    __typenames__ = ["double"]

    __dimensions__ = [None]

    def __init__(self):
        self.pitch_rad = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_camera_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.pitch_rad))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_camera_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_camera_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_camera_command()
        self.pitch_rad = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_camera_command in parents: return 0
        tmphash = (0xd94d812e4a314d89) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_camera_command._packed_fingerprint is None:
            lcmt_camera_command._packed_fingerprint = struct.pack(">Q", lcmt_camera_command._get_hash_recursive([]))
        return lcmt_camera_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_camera_command._get_packed_fingerprint())[0]

