"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import uav_delivery

class lcmt_timestamped_saved_traj(object):

    __slots__ = ["utime", "saved_traj"]

    __typenames__ = ["int64_t", "uav_delivery.lcmt_saved_traj"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.saved_traj = uav_delivery.lcmt_saved_traj()
        """ LCM Type: uav_delivery.lcmt_saved_traj """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_timestamped_saved_traj._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.saved_traj._get_packed_fingerprint() == uav_delivery.lcmt_saved_traj._get_packed_fingerprint()
        self.saved_traj._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_timestamped_saved_traj._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_timestamped_saved_traj._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_timestamped_saved_traj()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.saved_traj = uav_delivery.lcmt_saved_traj._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_timestamped_saved_traj in parents: return 0
        newparents = parents + [lcmt_timestamped_saved_traj]
        tmphash = (0x8ba151badcd25668+ uav_delivery.lcmt_saved_traj._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_timestamped_saved_traj._packed_fingerprint is None:
            lcmt_timestamped_saved_traj._packed_fingerprint = struct.pack(">Q", lcmt_timestamped_saved_traj._get_hash_recursive([]))
        return lcmt_timestamped_saved_traj._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_timestamped_saved_traj._get_packed_fingerprint())[0]

