"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import uav_delivery

class lcmt_saved_traj(object):

    __slots__ = ["num_trajectories", "trajectories", "trajectory_names"]

    __typenames__ = ["int32_t", "uav_delivery.lcmt_trajectory_block", "string"]

    __dimensions__ = [None, ["num_trajectories"], ["num_trajectories"]]

    def __init__(self):
        self.num_trajectories = 0
        """ LCM Type: int32_t """
        self.trajectories = []
        """ LCM Type: uav_delivery.lcmt_trajectory_block[num_trajectories] """
        self.trajectory_names = []
        """ LCM Type: string[num_trajectories] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_saved_traj._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_trajectories))
        for i0 in range(self.num_trajectories):
            assert self.trajectories[i0]._get_packed_fingerprint() == uav_delivery.lcmt_trajectory_block._get_packed_fingerprint()
            self.trajectories[i0]._encode_one(buf)
        for i0 in range(self.num_trajectories):
            __trajectory_names_encoded = self.trajectory_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__trajectory_names_encoded)+1))
            buf.write(__trajectory_names_encoded)
            buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_saved_traj._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_saved_traj._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_saved_traj()
        self.num_trajectories = struct.unpack(">i", buf.read(4))[0]
        self.trajectories = []
        for i0 in range(self.num_trajectories):
            self.trajectories.append(uav_delivery.lcmt_trajectory_block._decode_one(buf))
        self.trajectory_names = []
        for i0 in range(self.num_trajectories):
            __trajectory_names_len = struct.unpack('>I', buf.read(4))[0]
            self.trajectory_names.append(buf.read(__trajectory_names_len)[:-1].decode('utf-8', 'replace'))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_saved_traj in parents: return 0
        newparents = parents + [lcmt_saved_traj]
        tmphash = (0xc650fb3207e927c8+ uav_delivery.lcmt_trajectory_block._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_saved_traj._packed_fingerprint is None:
            lcmt_saved_traj._packed_fingerprint = struct.pack(">Q", lcmt_saved_traj._get_hash_recursive([]))
        return lcmt_saved_traj._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_saved_traj._get_packed_fingerprint())[0]

