"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_quadrotor_state(object):

    __slots__ = ["utime", "position", "velocity", "rotation", "rpy", "body_angular_velocity"]

    __typenames__ = ["int64_t", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, [3], [3], [9], [3], [3]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.velocity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.rotation = [ 0.0 for dim0 in range(9) ]
        """ LCM Type: double[9] """
        self.rpy = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.body_angular_velocity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_quadrotor_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>3d', *self.velocity[:3]))
        buf.write(struct.pack('>9d', *self.rotation[:9]))
        buf.write(struct.pack('>3d', *self.rpy[:3]))
        buf.write(struct.pack('>3d', *self.body_angular_velocity[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_quadrotor_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_quadrotor_state._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_quadrotor_state()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>3d', buf.read(24))
        self.velocity = struct.unpack('>3d', buf.read(24))
        self.rotation = struct.unpack('>9d', buf.read(72))
        self.rpy = struct.unpack('>3d', buf.read(24))
        self.body_angular_velocity = struct.unpack('>3d', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_quadrotor_state in parents: return 0
        tmphash = (0x420b1de7a39ce65) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_quadrotor_state._packed_fingerprint is None:
            lcmt_quadrotor_state._packed_fingerprint = struct.pack(">Q", lcmt_quadrotor_state._get_hash_recursive([]))
        return lcmt_quadrotor_state._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_quadrotor_state._get_packed_fingerprint())[0]

