"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_moving_target_state(object):

    __slots__ = ["utime", "timestamp_millis", "x", "y", "yaw", "vx", "vy", "yaw_rate", "left_wheel_angle_front", "left_wheel_angle_rear", "right_wheel_angle_front", "right_wheel_angle_rear"]

    __typenames__ = ["int64_t", "int64_t", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.timestamp_millis = 0
        """ LCM Type: int64_t """
        self.x = 0.0
        """ LCM Type: double """
        self.y = 0.0
        """ LCM Type: double """
        self.yaw = 0.0
        """ LCM Type: double """
        self.vx = 0.0
        """ LCM Type: double """
        self.vy = 0.0
        """ LCM Type: double """
        self.yaw_rate = 0.0
        """ LCM Type: double """
        self.left_wheel_angle_front = 0.0
        """ LCM Type: double """
        self.left_wheel_angle_rear = 0.0
        """ LCM Type: double """
        self.right_wheel_angle_front = 0.0
        """ LCM Type: double """
        self.right_wheel_angle_rear = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_moving_target_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqdddddddddd", self.utime, self.timestamp_millis, self.x, self.y, self.yaw, self.vx, self.vy, self.yaw_rate, self.left_wheel_angle_front, self.left_wheel_angle_rear, self.right_wheel_angle_front, self.right_wheel_angle_rear))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_moving_target_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_moving_target_state._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_moving_target_state()
        self.utime, self.timestamp_millis, self.x, self.y, self.yaw, self.vx, self.vy, self.yaw_rate, self.left_wheel_angle_front, self.left_wheel_angle_rear, self.right_wheel_angle_front, self.right_wheel_angle_rear = struct.unpack(">qqdddddddddd", buf.read(96))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_moving_target_state in parents: return 0
        tmphash = (0xd09336368d9c35ac) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_moving_target_state._packed_fingerprint is None:
            lcmt_moving_target_state._packed_fingerprint = struct.pack(">Q", lcmt_moving_target_state._get_hash_recursive([]))
        return lcmt_moving_target_state._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_moving_target_state._get_packed_fingerprint())[0]

