"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_quadrotor_setpoint(object):

    __slots__ = ["utime", "mode", "position", "velocity", "acceleration", "yaw", "yaw_rate"]

    __typenames__ = ["int64_t", "int8_t", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, [3], [3], [3], None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.mode = 0
        """
        0 = position-driven, 1 = pure velocity, 2 = direct attitude/thrust-compatible feedforward mode
        LCM Type: int8_t
        """

        self.position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.velocity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.acceleration = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.yaw = 0.0
        """ LCM Type: double """
        self.yaw_rate = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_quadrotor_setpoint._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.utime, self.mode))
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>3d', *self.velocity[:3]))
        buf.write(struct.pack('>3d', *self.acceleration[:3]))
        buf.write(struct.pack(">dd", self.yaw, self.yaw_rate))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_quadrotor_setpoint._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_quadrotor_setpoint._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_quadrotor_setpoint()
        self.utime, self.mode = struct.unpack(">qb", buf.read(9))
        self.position = struct.unpack('>3d', buf.read(24))
        self.velocity = struct.unpack('>3d', buf.read(24))
        self.acceleration = struct.unpack('>3d', buf.read(24))
        self.yaw, self.yaw_rate = struct.unpack(">dd", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_quadrotor_setpoint in parents: return 0
        tmphash = (0x84d907fca7204167) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_quadrotor_setpoint._packed_fingerprint is None:
            lcmt_quadrotor_setpoint._packed_fingerprint = struct.pack(">Q", lcmt_quadrotor_setpoint._get_hash_recursive([]))
        return lcmt_quadrotor_setpoint._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_quadrotor_setpoint._get_packed_fingerprint())[0]

