"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_raruco_detection(object):

    __slots__ = ["utime", "timestamp_millis", "detected", "marker_id", "confidence", "mean_abs_error", "center_u", "center_v", "polygon_area_px", "normal_alignment", "in_frame_fraction", "corner_u", "corner_v", "position_C"]

    __typenames__ = ["int64_t", "int64_t", "int8_t", "int32_t", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, [4], [4], [3]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.timestamp_millis = 0
        """ LCM Type: int64_t """
        self.detected = 0
        """ LCM Type: int8_t """
        self.marker_id = 0
        """ LCM Type: int32_t """
        self.confidence = 0.0
        """ LCM Type: double """
        self.mean_abs_error = 0.0
        """ LCM Type: double """
        self.center_u = 0.0
        """ LCM Type: double """
        self.center_v = 0.0
        """ LCM Type: double """
        self.polygon_area_px = 0.0
        """ LCM Type: double """
        self.normal_alignment = 0.0
        """ LCM Type: double """
        self.in_frame_fraction = 0.0
        """ LCM Type: double """
        self.corner_u = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """
        self.corner_v = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """
        self.position_C = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_raruco_detection._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqbiddddddd", self.utime, self.timestamp_millis, self.detected, self.marker_id, self.confidence, self.mean_abs_error, self.center_u, self.center_v, self.polygon_area_px, self.normal_alignment, self.in_frame_fraction))
        buf.write(struct.pack('>4d', *self.corner_u[:4]))
        buf.write(struct.pack('>4d', *self.corner_v[:4]))
        buf.write(struct.pack('>3d', *self.position_C[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_raruco_detection._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_raruco_detection._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_raruco_detection()
        self.utime, self.timestamp_millis, self.detected, self.marker_id, self.confidence, self.mean_abs_error, self.center_u, self.center_v, self.polygon_area_px, self.normal_alignment, self.in_frame_fraction = struct.unpack(">qqbiddddddd", buf.read(77))
        self.corner_u = struct.unpack('>4d', buf.read(32))
        self.corner_v = struct.unpack('>4d', buf.read(32))
        self.position_C = struct.unpack('>3d', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_raruco_detection in parents: return 0
        tmphash = (0x4b62debd34a232fc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_raruco_detection._packed_fingerprint is None:
            lcmt_raruco_detection._packed_fingerprint = struct.pack(">Q", lcmt_raruco_detection._get_hash_recursive([]))
        return lcmt_raruco_detection._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_raruco_detection._get_packed_fingerprint())[0]

